name: Run Locust Tests on Commit
on:
  push:
    branches:
      - main
jobs:
  locust-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip to the latest version
          pip install -r requirements.txt  # Install project dependencies from requirements.txt
      - name: Start Flask server
        run: |
          python server.py 3000 & 
          echo "Waiting for Flask server to start"
          sleep 30

      - name: Run Locust load test
        run: |
          locust -f locustfile.py --host=http://localhost:4000 --users=10000 --spawn-rate=100 -t 2m